import careerSenseLogo from "../Assets/CSlogo.png";

export const careerSenseClerkAppearance = {
  layout: {
    logoImageUrl: careerSenseLogo,
    logoLinkUrl: "/",
    logoPlacement: "inside",
    unsafe_disableDevelopmentModeWarnings: true,
  },
  variables: {
    colorPrimary: "#0EA8B9",
    colorBackground: "#F8FBFF",
    colorInputBackground: "#FFFFFF",
    colorInputText: "#071536",
    colorText: "#071536",
    colorTextSecondary: "#5E6F89",
    colorNeutral: "#17304F",
    borderRadius: "0.875rem",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
  },
  elements: {
    card: "border border-cyan-100 shadow-[0_28px_80px_rgba(7,26,56,0.22)]",
    modalBackdrop: "bg-[#041024]/65 backdrop-blur-[2px]",
    navbar: "border-r border-cyan-100 bg-gradient-to-b from-[#F1F8FF] to-[#EAF7F7]",
    navbarButton: "rounded-xl text-[#52627C] hover:bg-white/80 hover:text-[#087F8A]",
    navbarButtonIcon: "text-[#0EA8B9]",
    activeNavbarButton: "bg-white text-[#071536] shadow-sm",
    headerTitle: "font-extrabold tracking-[-0.025em] text-[#071536]",
    headerSubtitle: "text-[#667792]",
    profileSectionTitleText: "font-extrabold text-[#071536]",
    profileSectionPrimaryButton: "font-bold text-[#087F8A] hover:text-[#0757E6]",
    formButtonPrimary: "bg-gradient-to-r from-[#0EA8B9] to-[#2563EB] font-extrabold shadow-[0_10px_24px_rgba(14,168,185,0.22)] hover:brightness-105",
    formFieldInput: "border-slate-200 bg-white focus:border-cyan-500 focus:ring-cyan-500/15",
    userButtonPopoverCard: "overflow-hidden border border-cyan-100 bg-[#F8FBFF] shadow-[0_22px_60px_rgba(7,26,56,0.2)]",
    userButtonPopoverMain: "bg-[#F8FBFF]",
    userButtonPopoverActionButton: "text-[#33445F] hover:bg-[#EAF7F7] hover:text-[#087F8A]",
    userButtonPopoverActionButtonIcon: "text-[#0EA8B9]",
    userPreview: "border-b border-cyan-100 bg-white",
    avatarBox: "ring-2 ring-cyan-500/25",
    footer: "hidden",
    userButtonPopoverFooter: "hidden",
    userProfileFooter: "hidden",
  },
};
